import { CarosalType } from "../components/Home/CarosalItemCard";

export const CarosalData: CarosalType[] = [
  {
    title: "Here come Holiday Specials",
    subtitle: "Explore now",
    image: [
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Holiday_deals_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Most_loved_deals_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Deals_under_50_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Deals_on_Computer_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Deals_on_Fashion_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Deals_on_Toys__Games_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Gift_guides_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Holiday_Fashion__1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Holiday_Home_Decor_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Electronics_Gift_Guide_1X_EN._CB541659723_.jpg",
      "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/Holiday_Shovler/Fuji_HolidayGG_Shoveler_Holiday_Toys_List_1X_EN._CB541659723_.jpg",
    ],
  },
];

export const CarosalData2: CarosalType[] = [
  {
    title: "New international customers purchased",
    subtitle: "",
    image: [
      "https://m.media-amazon.com/images/I/61nHUVwR65L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61u0Nv-aFdL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/515mpWFDqpL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/618JQO31dTL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81dyDzYVacS._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61zwP1xM9aL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/718K-c0A7eL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71Ky2jFoPEL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71oCtwijE2L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71cwPMSk6ZL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61yhtKVPFGL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71X27N2NBpL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81q+61jTdFL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61FworBrvlL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61W7UV4z+SL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/710H3Aeo0iL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81n-ap+0lPL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71eL6cpT+pL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71zvPJqU7FL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/21o8on38lRL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61QeFfa1tBL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71Kz8HU27ML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71t5zvbtCoL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61I3uveR-5L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61qKu6T1D6L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71LgEOkGCsL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71EAKTri6IL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/713lDYWESmL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71EkRSfQCgL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61OyiBG3eWL._AC_SY200_.jpg",
    ],
  },
];

export const CarosalData3: CarosalType[] = [
  {
    title: "International top sellers",
    subtitle: "",
    image: [
      "https://m.media-amazon.com/images/I/61aOVk7w1CL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/21cyLLAmtNL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81DC7pBBdOL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/710H3Aeo0iL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/5107bLPQ8EL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71CcdJTzvnL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71EkRSfQCgL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61AAeKrRj9L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81n-ap+0lPL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61I1fmgWJgL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71LgEOkGCsL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71Ky2jFoPEL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71SPdJ2CF5L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61b3vWCzFxL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61Gf5zvp43L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61rTh6HyrOL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51AMYge+zHL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71cwPMSk6ZL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71BBPx7mB4L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61yhtKVPFGL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/719lmenv8JL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61FworBrvlL._AC_SY200_.jpg",
    ],
  },
];

export const CarosalData4: CarosalType[] = [
  {
    title: "Most wished for in Movies & TV",
    subtitle: "",
    image: [
      "https://m.media-amazon.com/images/I/81augjJBSVL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81fBb0Z1egL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71G0oOmuZdL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71h7HHb9lIL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/91zGP84MoGL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/7134nPYDHNL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71mp7b4jftL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71VX9I9YLQL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/91Mn8RRd2tL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81m2T+QXr4L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71Z-9Z9ktbL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81rYwN4hV4L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/8144UsWiG8L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81OSp+wQlAL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81M0ADtxVwL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/713fVgRt3uL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71lrfeXjuVL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71V2NJ9U7sL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71ZNyTPaV1L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/212z2jQTi1L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71xagWGOdoL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61djSzfUC8L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81osXopbFqL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/91tovnZKvbL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71-yconZqKL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81khSUgP0HL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81hX8sWaIEL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71evuls8RHL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/9139RIJAseL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71LXlYMccGL._AC_SY200_.jpg",
    ],
  },
];

export const CarosalData5: CarosalType[] = [
  {
    title: "Best Sellers in Home & Kitchen",
    subtitle: "",
    image: [
      "https://m.media-amazon.com/images/I/51zaCVh6SIL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61kdWPk5E3L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71M6a8SHCeL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/711Pd4pAs3L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81-x+F2EsHL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81s15a8-lGL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51l1Mznj73L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71329CVoVDL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51lVmYVNYhL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81CGKCHLbML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/713afJ6oJ+L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/41Ai-GLQzQL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/31y1VC+JsML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/A1Ajfh3EvtL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61eqNRPW8mL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81bpKKv68-L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71LOYxu6SAL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61xFTk0T7fL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71nhPE7vxHL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81oOlGr02ML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/613SIcuykuL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/616khde2emL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81Lv7sV-6-L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81yeSy2PbtL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81cLNKAxaBL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/8103b-xN7kL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71LmN7FsaZL._AC_SY200_.jpg",
    ],
  },
];

export const CarosalData6: CarosalType[] = [
  {
    title: "Best Sellers in Cell Phones & Accessories",
    subtitle: "",
    image: [
      "https://m.media-amazon.com/images/I/51rRDJJRtSL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71ujCXmXeRL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71f4mqy9BjL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/714ozPCsxiL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61ODqzlY4ML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71FOmDX3yWL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51+oaOVMYtL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71JLo9DxMnL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61VwfUI+-eL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/414C25OyjML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71OicfvCsbL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/41GcNSsstaL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71fW+RXbrzL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61lzntb+BnL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51JMXGSMcTL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/41WyiWOMq0L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61+dhCLooPL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71zY7rMNyjL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/6139YlK0EDL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/21SPDoiRuGL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61k6AgcmR6L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71S7Ej-DfQL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71+Wm7WhO5L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/7154009guGL._AC_SY200_.jpg",
    ],
  },
];
